---
kind: pipeline
name: default
type: docker

steps:
  - name: fetch
    image: alpine/git
    commands:
      - git fetch --tags

  - name: lint
    image: golangci/golangci-lint:v1.31.0-alpine
    commands:
      - apk add --no-cache make
      - make lint

  - name: test
    image: golang
    pull: always
    commands:
      - make test

  - name: build
    image: goreleaser/goreleaser
    commands:
      - make build
    depends_on:
      - test
      - lint
    when:
      event:
        exclude:
          - tag

  - name: release
    image: golang
    environment:
      GITEA_TOKEN:
        from_secret: gitea_token
      DOCKER_USERNAME:
        from_secret: username
      DOCKER_PASSWORD:
        from_secret: password
      DOCKER_REGISTRY: quay.io
    commands:
      - curl -sL https://git.io/goreleaser | bash
    depends_on:
      - test
      - lint
    when:
      event: tag
  # - name: docker
  #   image: plugins/docker
  #   settings:
  #     repo: quay.io/xsteadfastx/jitsiexporter
  #     registry: quay.io
  #     auto_tag: true
  #     username:
  #       from_secret: username
  #     password:
  #       from_secret: password
  #   when:
  #     event: tag
